# options for analysis running
run:
  # default concurrency is an available CPU number
  concurrency: 4

  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 5m

  # include test files or not, default is true
  tests: true

# settings of specific linters
linters-settings:
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 10

linters:
  # do not use `enable-all`: it's deprecated and will be removed soon.
  disable-all: true
  # gosec linter is disabled until we find out how to get it work properly with golangci-lint
  # use 'gosec ./...' command
  enable:
    - asciicheck
    - depguard
    - dogsled
    - errcheck
    - gocognit
    - goconst
    - gocritic
    - gofmt
    - goimports
    - revive
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  max-same-issues: 0
